
const TeamComponent =  [{
    id: "1",
    img: "https://i.pinimg.com/originals/09/24/a7/0924a7ef295741e916c8f42512bbe5bd.jpg",
    name: "Ajay Pathak",
    place: "Gurugram, Haryana",
    company: "Naehas Inc",
    designation: "Frontend Developer",
  },
  {
    id: "2",
    img: "https://t4.ftcdn.net/jpg/03/22/27/15/360_F_322271599_m6B4XfH1Y2k72n5Kk34Q1KfX7oz3GlQs.jpg",
    name: "Balaji Gaikwad",
    place: "Pune, Maharashtra",
    company: "Nice Ltd",
    designation: "Senior Software Engineer",
  },
  {
    id: "3",
    img: "https://i.pinimg.com/originals/23/92/fb/2392fb7e5f3b36bfbeca4ff575a7eca0.png",
    name: "Chaitra J",
    place: "Bengaluru, Karnataka",
    company: "Wells Fargo",
    designation: "Senior Software Engineer",
  },
  {
    id: "4",
    img: "https://cdn3.vectorstock.com/i/1000x1000/28/92/cute-boy-cartoon-vector-16632892.jpg",
    name: "Gourav Goswami",
    place: "Madhya Pradesh",
    company: "Toschi Infotech",
    designation: "Frontend Developer",
  },
  {
    id: "5",
    img: "https://image.winudf.com/v2/image1/Y29tLmxha25haWRyaWFwcHMuZ2lybHNjYXJ0b29uX3NjcmVlbl85XzE2Mjg5NDQxNjJfMDQz/screen-9.jpg?fakeurl=1&type=.webp",
    name: "Kirti Sahai",
    place: "New Delhi",
    company: "Kongsberg Digital",
    designation: "Senior Frontend Developer",
  },
  {
    id: "6",
    img: "https://wallpaperaccess.com/full/4588325.jpg",
    name: "Laxmi Waghmore",
    place: "Mumbai, Maharashtra",
    company: "Cognizant",
    designation: "Frontend Developer",
  },
  {
    id: "7",
    img: "https://previews.123rf.com/images/tigatelu/tigatelu1311/tigatelu131100129/23848481-cute-boy-cartoon-reading-book.jpg",
    name: "Mallikarjun K Basavanagowdra",
    place: "Bengaluru, Karnataka",
    company: "William O'Neil India",
    designation: "Software Engineer",
  },
  {
    id: "8",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2XYxKZOxIWSSBNkVs1vAd1tRI5WgDILFLbg&usqp=CAUg",
    name: "Pujarini Jena",
    place: "Gurugram, Haryana",
    company: "CARS24",
    designation: "Software Engineer",
  },
  {
    id: "9",
    img: "https://t4.ftcdn.net/jpg/01/11/38/83/360_F_111388365_BLOhQUq1PGERnzkyqbdLMGRzp15nykT0.jpg",
    name: "Roshan Trivedi",
    place: "Muzaffarpur, Bihar",
    company: "Infosys",
    designation: "",
  },
  {
    id: "10",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRmquQECZWY0VKxhlU4wLFYo6oMiE9RFJuLg&usqp=CAU",
    name: "Vijesh N K",
    place: "Mangalore, Karnataka",
    company: "Pace wisdom solutions",
    designation: "",
  },
];

export default TeamComponent; //Default Exports is useful to export at one time and can be used any different name while importing.